version: '3'

services:
  front:
    image: 'frontend'
    container_name: 'frontend'
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - '5173:5173'
    volumes:
      - './app:/app'
      - '/app/node_modules'